/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "axvqdmnnwtsfvpaycovo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dnFkbW5ud3RzZnZwYXljb3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MzQyMjIsImV4cCI6MjA3OTExMDIyMn0.3nK3XAQfGcbJD_IZfNOQS86-k2eB1RgtowGz-FLPNac"